version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
#      - post_db:/data/db
      - post_db:${VOL_PATH_DB}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
#    image: ${USERNAME}/ui:1.0
    image: ${USERNAME}/ui:${VER_UI}
    ports:
#      - 9292:9292/tcp
      - ${PORT_UI}:${PORT_UI}/tcp
    networks:
      - front_net
      
  post:
    build: ./post-py
#    image: ${USERNAME}/post:1.0
    image: ${USERNAME}/post:${VER_POST}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
              
  comment:
    build: ./comment
#    image: ${USERNAME}/comment:1.0
    image: ${USERNAME}/comment:${VER_COMMENT}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post

volumes:
  post_db:

#networks:
#  reddit:
  
networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:  
        - subnet: 10.0.1.0/24
